import numpy as np


class UniformFlow:
    """
    Contains information related to a uniform flow.
    """

    def __init__(self, u_inf: float, alpha: float):
        """
        Sets velocity and angle of attack of the uniform flow.

        Parameters
        ----------
        u_inf: float
            Velocity of the uniform flow.
        alpha: float
            Angle of attack of the uniform flow.
        """
        self.u_inf = u_inf
        self.alpha = alpha

    def velocity(self, x, y):
        """
        Returns the uniform velocity field.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u = self.u_inf * np.cos(np.radians(self.alpha)) * np.full_like(x, 1)
        v = self.u_inf * np.sin(np.radians(self.alpha)) * np.full_like(y, 1)
        return u, v

    def stream_function(self, x, y):
        """
        Computes the stream-function uniform flow.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the source.
        """
        psi = self.u_inf * y * np.cos(np.radians(self.alpha)) - self.u_inf * x * np.sin(
            np.radians(self.alpha)
        )
        return psi


class Source:
    """
    Contains information related to a source (or sink).
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the singularity.

        Parameters
        ----------
        strength: float
            Strength of the singularity.
        x: float
            x-coordinate of the singularity.
        y: float
            y-coordinate of the singularity.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x, y):
        """
        Computes the velocity field generated by the singularity.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u = (
            self.strength
            / (2 * np.pi)
            * (x - self.x)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        v = (
            self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return u, v

    def stream_function(self, x, y):
        """
        Computes the stream-function generated by the singularity.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the source.
        """
        psi = self.strength / (2 * np.pi) * np.arctan2((y - self.y), (x - self.x))
        return psi


class Vortex:
    """
    Contains information related to a vortex.
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the vortex.

        Parameters
        ----------
        strength: float
            Strength of the vortex.
        x: float
            x-coordinate of the vortex.
        y: float
            y-coordinate of the vortex.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x, y):
        """
        Computes the velocity field generated by a vortex.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the vortex.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the vortex.
        """
        u = (
            +self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        v = (
            -self.strength
            / (2 * np.pi)
            * (x - self.x)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return u, v

    def stream_function(self, x, y):
        """
        Computes the stream-function generated by a vortex.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the vortex.
        """
        psi = (
            -self.strength / (4 * np.pi) * np.log((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return psi


class Doublet:
    """
    Contains information related to a doublet.
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the doublet.

        Parameters
        ----------
        strength: float
            Strength of the doublet.
        x: float
            x-coordinate of the doublet.
        y: float
            y-coordinate of the doublet.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x, y):
        """
        Computes the velocity field generated by a doublet.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the doublet.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the doublet.
        """
        u = (
            -self.strength
            / (2 * np.pi)
            * ((x - self.x) ** 2 - (y - self.y) ** 2)
            / ((x - self.x) ** 2 + (y - self.y) ** 2) ** 2
        )
        v = (
            -self.strength
            / (2 * np.pi)
            * 2
            * (x - self.x)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2) ** 2
        )
        return u, v

    def stream_function(self, x, y):
        """
        Computes the stream-function generated by a doublet.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the doublet.
        """
        psi = (
            -self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return psi
